default: &default
  adapter: postgresql
  encoding: unicode
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  pool: 5 
  user: <%= ENV.fetch('POSTGRES_USER') %>

test:
  <<: *default
  database: KubernetesDemoApp_test

development:
  <<: *default
  database: KubernetesDemoApp_development

production:
  <<: *default
  database: KubernetesDemoApp_production
